package book.operators;

import static book.util.Print.print;

public class SignedRightShiftExercise11 {
    public static void main(String[] args) {
        int i = 0x80000000;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
        i >>= 1;
        print(Integer.toBinaryString(i));
    }
}
