# Use root/example as user/password credentials
version: '3.8'

services:

  mysql:
    image: mysql:8.0.33
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sbur
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql-db:/var/lib/mysql

  mongo:
    image: mongo:6.0.5
#    container_name: mongo
#    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo-db:/var/lib/mongo
    ports:
      - "27017:27017"

  neo4j:
    image: neo4j:4.4.20
    #    container_name: mongo
    #    hostname: mongo
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/secret
    volumes:
      - neo4j-db:/var/lib/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8060:8080"

volumes:
  mysql-db:
  mongo-db:
  neo4j-db: